version: '3'

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - .:/src
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    links:
      - web

  web:
    build: .
    image: techatomanswers:latest
    volumes:
      - .:/src
